---

#
# bootstrap python3-libdnf5
#

- name: Run playbook-all_nodes-bootstrap_python3-libdnf5.yml
  ansible.builtin.import_playbook: playbook-all_nodes-bootstrap_python3-libdnf5.yml

#
# general configuration
#

- name: Run playbook-all_nodes-create_a_vimrc.yml
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: Run playbook-all_nodes-install_tmux.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: Run playbook-all_nodes-minimal_tmux_configuration.yml
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: Run playbook-all_nodes-minimal_bashrc.yml
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: Run playbook-all_nodes-update_all_packages.yml
  ansible.builtin.import_playbook: playbook-all_nodes-update_all_packages.yml

- name: Run playbook-all_nodes-set_SELINUX_to_permissive.yml
  ansible.builtin.import_playbook: playbook-all_nodes-set_SELINUX_to_permissive.yml

#
# MariaDB
#

- name: Run playbook-all_nodes-install_and_start_mariadb.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_and_start_mariadb.yml

- name: Run playbook-all_nodes-configure_a_mariadb_database.yml
  ansible.builtin.import_playbook: playbook-all_nodes-configure_a_mariadb_database.yml

#
# Ghost
#

- name: Run playbook-all_nodes-create_the_ghost_user.yml
  ansible.builtin.import_playbook: playbook-all_nodes-create_the_ghost_user.yml

- name: Run playbook-all_nodes-install_dependencies.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_dependencies.yml

- name: Run playbook-all_nodes-install_ghost-cli.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_ghost-cli.yml

- name: Run playbook-all_nodes-install_ghost.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_ghost.yml

- name: Run playbook-all_nodes-output_URLs.yml
  ansible.builtin.import_playbook: playbook-all_nodes-output_URLs.yml
