---
- name: 'Output the URLs'
  hosts: 'all'
  gather_facts: true
  become: false

  tasks:

    - name: 'Wait for the Ghost URL to be reachable'
      ansible.builtin.uri:
        url: "http://ghost.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.sslip.io"
      register: result
      until: |
        result.status == 200
      retries: 31
      delay: 10

    - name: 'Ghost URL'
      ansible.builtin.debug:
        msg: "URL: http://ghost.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.sslip.io"

    - name: 'Ghost admin URL'
      ansible.builtin.debug:
        msg: "Create your account here: http://ghost.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.sslip.io/ghost/"
