---
- name: Set SELINUX to permissive
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:

    - name: Install python3-libselinux
      ansible.builtin.package:
        name: python3-libselinux

  roles:

    - role: johanneskastl.set_SELINUX_to_permissive
      when:
        - ansible_os_family == "RedHat" or ansible_os_family == "Rocky"
